### ISSUE TITLE
Download pre-generated afdb.tar.gz

### ISSUE THREAD

**Issue by LTEnjoy** [steineggerlab/foldseek#202]
Hi!

Thank you for providing such pre-generated databases for use. I wonder how can I download the largest afdb database as I found foldseek doesn't support it when I tried to use ``foldseek databases`` command.

Thank you in advance!

**Comment by milot-mirdita** [comment]
The full afdb is now part of the afdb50 download too, the afdb50 can be searched in clustered search mode where it expands the search results based on the found cluster representative or it you can use the afdb50_seq database which contains the full afdb (needed for cluster expansion).

Sorry for the confusing databases, we don’t want to store the afdb twice since we pay per month per gb of cloud storage.

**Comment by LTEnjoy** [comment]
Thanks for the answer! Previously I asked how to recover all 3Di sequences from a pre-generated database. Can I recover all 3Di sequences in the UniProt database given the afdb50? If can, which commands should I use?

Looking forward to your reply and thanks in advance!

**Comment by milot-mirdita** [comment]
Yes you can use the afdb50_seq_ss analogous to the commands in the other thread to create a FASTA file with 3di sequences

**Comment by LTEnjoy** [comment]
OK, I will try it out. Thank you very much!
