### ISSUE TITLE
Finding remote matches with low TM-score

### ISSUE THREAD

**Issue by tomsercu** [steineggerlab/foldseek#72]
Hi Martin and foldseek team, 
I'm trying to improve some intuition about foldseek; specifically regarding foldseek search returning weak matches of a query structure with TM-score < 0.5, let's say in the `[0.3 - 0.5]` range. By default foldseek returns no such matches, I think purely due to the default `--tmscore-threshold 0.5`, correct? It seems to me that lowering the `--tmscore-threshold` to increase recall would quickly get problematic due to increased false negative rate for those weak matches, as I think the lower-TM matches would get pruned out by the prefilters. So those lower TM-scores would get quite unreliable and not that meaningful. Do you agree with this intuition or would you expect foldseek to still be reliable in the `[0.3-0.5]` range?
Thanks!
Tom

**Comment by martin-steinegger** [comment]
Thank you for posting this question Tom. 

It is important to be careful when using the `--tmscore-threshold` parameter in foldseek, as its behavior depends on the alignment type used and this might have different consequences (see below).

By default, foldseek uses a 3Di/AA alignment, which allows you to use TMscore for filtering. However, the TMscore is normalized by the alignment length to maintain the local alignment property. This means that it can be difficult to determine if a TMscore of 0.3-0.5 is sufficient, as very small alignments could produce high TMscores. You should consider both the TMscore and the alignment length when evaluating results. Personally, I tend to use the e-value in foldseek because it follows the BLAST scheme and is easier to work with. Alternatively, you could use our homology probability (output field `prob`), which doesn't have the same limitations as TMscore and isn't affected by the size of the database. 

If you use the `--alignment-type 1` option, which is our TMalign mode, the TMscore is not symmetrical and depends on the use case. In foldseek, we report the query-normalized score by default. However, the target-normalized score may be more relevant in some cases. For example, if you align a longer query structure against a smaller target structure in a database (e.g. a fragment), the query-normalized score may be low (e.g. 0.3), while the target-normalized score may be high (e.g. 0.5). Recently, we realized that there are limitations to using TMscore alone to rank hits. To address this, we sorted the hits by the average TMscore of the query and target structures, which often improves ranking, especially when searching for globally alignable hits.

There are also situations where TMscore may not be the most reliable measure, such as when searching for multi-domain hits where one domain is flexible. In these cases, it may be better to use LDDT instead. With the latest release of foldseek, we can report the alignment LDDT.
