### ISSUE TITLE
How to quentify the data by 3Di/AA mode?

### ISSUE THREAD

**Issue by yang-nei** [steineggerlab/foldseek#98]
I execute Foldseek with 3Di/AA mode, I am confused whether E-value  can be distinguished like TM-score with confidence levels(very confidence, Confidence, suspect, unconfidence) and what scores can be therholds.

**Comment by martin-steinegger** [comment]
Foldseek employs a well-calibrated, BLAST-like E-value to assess the statistical significance of structural alignments. Lower E-values represent more significant matches, with a reduced likelihood of chance occurrences. E-values are influenced by database size. Hits with an E-value below 0.1 are generally considered homologous. For hits with E-values larger than 0.1, we introduced a probability (`prob`) to help determine the likelihood of homology, helping to judge distance hit better. The `prob` is not database size dependent.

**Comment by yang-nei** [comment]
Thanks for your reply!However,I have read your paper "Clustering predicted structures at the scale of the known protein universe" in that paper you take advantage of 10^-3, 10^-5 as the E-value thresholds. And I don't understand how to definite the data with proper E-value.

**Comment by martin-steinegger** [comment]
Setting the E-value threshold depends on the specific use-case. For instance, in clustering scenarios, millions of structures are compared against each other, which means that even with a relatively strict threshold, errors are expected. Therefore, we opted for a more stringent approach during the clustering process, sacrificing some sensitivity in order to minimize the number of false positives per cluster.
